[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version="1.0.205", features = ["derive"] }
serde_json = "1.0"
mongodb = "3.0.1"
tokio = { version = "1.39.2", features = ["full"] }
uuid = "1.2"
futures-util = "0.3"